services:
  resume-site:
    image: resume-site
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./app:/usr/share/nginx/html
